#该项目启动的配置文件，可见application-demo.properties上面的说明，我只是把它改成了yml配置
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9077
spring:
  datasource:
    url: jdbc:mysql://192.168.46.117:3306/zzxtest
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jpa:
    show-sql: true
    format-sql: true
    use-sql-comments: true
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates
#日志配置
logging:
  level:
    #配置打印sql,com.zzx 这个和mybatis的configuration.log-prefix配置有关系
    com.zzx.sql: debug
    root: info
  path: logs
  file: zzx.log
  config: classpath:logging.xml
mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath*:mapper/*.xml 
  # 注意：对应实体类的路径
  type-aliases-package: com.zzx.*.entity
  #检查 mybatis 配置是否存在
  check-config-location: true
  #执行模式。默认是 SIMPLE
  executor-type: simple
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    ##指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射\u3000PARTIAL:部分  FULL:全部
    auto-mapping-behavior: full
    log-prefix: com.zzx.sql.
    ##使全局的映射器启用或禁用缓存。
    cache-enabled: false
    local-cache-scope: statement
    jdbc-type-for-null: 'null'
#tkmybatis指定通用mapper位置
mapper:
  mapers: com.tk.mapper.MyMapper
  identity: MYSQL
#分页助手的配置	
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#关闭Ribbon的重试机制（如果有必要）
ribbon:
  MaxAutoRetriesNextServer:0
  ReadTimeout:5000
  ConnectTimeout:5000
  
## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled:true